In [2]:
import numpy as np

In [3]:
x1 = np.arange(9.0).reshape((3,3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [5]:
x2 = np.arange(10, 19).reshape((3,3))
x2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
x1 * x2

array([[  0.,  11.,  24.],
       [ 39.,  56.,  75.],
       [ 96., 119., 144.]])

In [8]:
(x1 * x2).sum(axis=1).reshape(-1,1) # * same as np.multiply

array([[ 35.],
       [170.],
       [359.]])

In [13]:
x1 @ x2 # same as np.matmul

array([[ 45.,  48.,  51.],
       [162., 174., 186.],
       [279., 300., 321.]])